import type { Finding, Manifest } from "./migrator.ts";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface MigrationBundle {
  protocol: string;
  generatedAt: string;
  summary: {
    callSites: number;
    savedCu: number;
    savingsPercent: number;
    files: number;
  };
  files: GeneratedFile[];
}

export function buildMigrationBundle(manifest: Manifest): MigrationBundle {
  const affectedFiles = new Set(manifest.findings.map((finding) => finding.file));
  return {
    protocol: manifest.protocol,
    generatedAt: new Date().toISOString(),
    summary: {
      callSites: manifest.totals.callSites,
      savedCu: manifest.totals.savedCu,
      savingsPercent: manifest.totals.savingsPercent,
      files: affectedFiles.size
    },
    files: [
      {
        path: "README.md",
        content: renderBundleReadme(manifest)
      },
      {
        path: "migration-plan.json",
        content: JSON.stringify(renderPlan(manifest), null, 2)
      },
      {
        path: "patches/p-token-replacements.rs",
        content: renderReplacementPatchFile(manifest.findings)
      },
      {
        path: "crates/p-token-shim-anchor/USAGE.md",
        content: renderShimUsage(manifest)
      }
    ]
  };
}

function renderBundleReadme(manifest: Manifest): string {
  return [
    `# ${manifest.protocol} p-token migration bundle`,
    "",
    "This bundle was generated by the p-token Migration Toolkit.",
    "",
    "## Summary",
    "",
    `- Call sites: ${manifest.totals.callSites}`,
    `- Files scanned: ${manifest.totals.filesScanned}`,
    `- Estimated CU saved: ${manifest.totals.savedCu}`,
    `- Estimated savings: ${manifest.totals.savingsPercent}%`,
    `- Dry-run status: ${manifest.simulation.status}`,
    "",
    "## Apply manually",
    "",
    "1. Add a switchable token-program account to each affected instruction context.",
    "2. Replace legacy SPL Token CPI calls with the generated shim calls in `patches/p-token-replacements.rs`.",
    "3. Run your Anchor tests against legacy SPL Token and p-token modes.",
    "4. Keep rollback support until final p-token mainnet behavior is validated.",
    "",
    "The generated patches are intentionally conservative. Review signer seeds, token authority constraints, and checked-operation decimal handling before shipping."
  ].join("\n");
}

function renderPlan(manifest: Manifest): unknown {
  return {
    schemaVersion: "0.1.0",
    protocol: manifest.protocol,
    generatedAt: manifest.generatedAt,
    profile: manifest.pTokenProfile,
    totals: manifest.totals,
    idlHints: manifest.idlHints,
    simulation: manifest.simulation,
    files: groupFindingsByFile(manifest.findings)
  };
}

function groupFindingsByFile(findings: Finding[]): Array<{ file: string; findings: Array<Record<string, unknown>> }> {
  const grouped = new Map<string, Finding[]>();
  for (const finding of findings) {
    grouped.set(finding.file, [...(grouped.get(finding.file) || []), finding]);
  }
  return Array.from(grouped.entries()).map(([file, fileFindings]) => ({
    file,
    findings: fileFindings.map((finding) => ({
      id: finding.id,
      line: finding.line,
      operation: finding.operation,
      risk: finding.risk,
      legacyCu: finding.compute.legacyCu,
      pTokenCu: finding.compute.pTokenCu,
      savedCu: finding.compute.savedCu
    }))
  }));
}

function renderReplacementPatchFile(findings: Finding[]): string {
  if (!findings.length) return "// No SPL Token CPI call sites were found.\n";
  return findings.map((finding) => [
    `// Finding: ${finding.id}`,
    `// Original: ${finding.snippet}`,
    finding.replacementPatch
  ].join("\n")).join("\n\n");
}

function renderShimUsage(manifest: Manifest): string {
  return [
    "# p-token shim usage",
    "",
    "Use the local `p-token-shim-anchor` crate as the transition boundary between legacy SPL Token and p-token CPI calls.",
    "",
    "```rust",
    "let selector = PTokenProgramSelector::new(legacy_program_id, p_token_program_id, selected_program_id);",
    "let operation = PTokenOperation::Transfer;",
    "let route = selector.route(operation);",
    "```",
    "",
    "Generated operation counts:",
    "",
    ...Object.entries(operationCounts(manifest.findings)).map(([operation, count]) => `- ${operation}: ${count}`),
    "",
    "Replace the crate internals with canonical p-token program IDs and instruction builders when those interfaces are finalized."
  ].join("\n");
}

function operationCounts(findings: Finding[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const finding of findings) {
    counts[finding.operation] = (counts[finding.operation] || 0) + 1;
  }
  return counts;
}
